### What is an API?

An API (Application Programming Interface) is a set of rules that allows different software applications to communicate with each other. It acts as a bridge between a client and a server, enabling one application to request data or services from another without needing to know how the underlying system works. For example, when a weather app shows current weather information, it usually gets that data from a weather API. APIs make software development faster, more secure, and more organized by providing a standard way for applications to exchange information.

In [1]:
import pandas as pd
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7b9d91bc379f746baff9690bb55ef791&language=en-US&page=1')

In [12]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [13]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,153.6512,8.971,1724
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,68.7965,8.723,30586
2,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,133.9242,8.683,5212
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,38.1178,8.687,23052
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,535.6645,8.658,2690

In [21]:
df = pd.DataFrame()

In [22]:
df

Empty DataFrame
Columns: []
Index: []

In [23]:
import requests
import pandas as pd

API_KEY = "7b9d91bc379f746baff9690bb55ef791"

# First request to get total pages
url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page=1"

response = requests.get(url)
data = response.json()

total_pages = data['total_pages']

dfs = []

for page in range(1, total_pages + 1):
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page={page}"

    response = requests.get(url)
    data = response.json()
    temp_df = pd.DataFrame(data['results'])[
        [
            'id',
            'title',
            'overview',
            'release_date',
            'popularity',
            'vote_average',
            'vote_count'
        ]
    ]

    dfs.append(temp_df)

df = pd.concat(dfs, ignore_index=True)

print(df.shape)
print(df.head())

KeyError: 'results'