In [1]:
import pandas as pd

## 1. Working with excel file

In [4]:
pd.read_excel('file_example_XLSX_5000.xlsx',index_col='Unnamed: 0')

     First Name   Last Name  Gender        Country  Age        Date    Id
1         Dulce       Abril  Female  United States   32  15/10/2017  1562
2          Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
3        Philip        Gent    Male         France   36  21/05/2015  2587
4      Kathleen      Hanner  Female  United States   25  15/10/2017  3549
5       Nereida     Magwood  Female  United States   58  16/08/2016  2468
...         ...         ...     ...            ...  ...         ...   ...
4996       Roma  Lafollette  Female  United States   34  15/10/2017  2654
4997     Felisa        Cail  Female  United States   28  16/08/2016  6525
4998   Demetria       Abbey  Female  United States   32  21/05/2015  3265
4999     Jeromy        Danz    Male  United States   39  15/10/2017  3265
5000   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

[5000 rows x 7 columns]

In [6]:
pd.read_excel('file_example_XLSX_5000.xlsx',index_col='Unnamed: 0',sheet_name='Sheet2')

     First Name   Last Name  Gender        Country  Age        Date    Id
4362   Franklyn      Unknow    Male         France   38  15/10/2017  2579
4363    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
4364     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
4365       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
4366   Shavonne         Pia  Female         France   24  21/05/2015  1546
...         ...         ...     ...            ...  ...         ...   ...
4996       Roma  Lafollette  Female  United States   34  15/10/2017  2654
4997     Felisa        Cail  Female  United States   28  16/08/2016  6525
4998   Demetria       Abbey  Female  United States   32  21/05/2015  3265
4999     Jeromy        Danz    Male  United States   39  15/10/2017  3265
5000   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

[639 rows x 7 columns]

## 2. Working with JSON :- 
* A lightweight format for **storing and exchanging data**.
* Human-readable and easy for machines to parse.
* Uses **key-value pairs**.
* Commonly used in **APIs**, web applications, and configuration files.
* Supports these data types:

  * String
  * Number
  * Boolean (`true`, `false`)
  * Array (`[]`)
  * Object (`{}`)
  * Null (`null`)

**Example:**

```json
{
  "name": "Aryan",
  "age": 20,
  "skills": ["Python", "JavaScript"],
  "isStudent": true
}
```

**Python Conversion:**

```python
import json

# Python dict → JSON
json_data = json.dumps(data)

# JSON → Python dict
python_data = json.loads(json_string)
```

**Remember:**
JSON is essentially a **text representation of a dictionary/object** used for data exchange between systems.

In [7]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [8]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.0389
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.6770
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.8740
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,3.9000
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,2.5300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.1740
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.1890
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.2830
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-20,1781913601,0.2840

## 3. Working with SQL

In [9]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -------------- ------------------------- 4.2/11.9 MB 23.4 MB/s eta 0:00:01
     -------------- ------------------------- 4.2/11.9 MB 23.4 MB/s eta 0:00:01
     ---------------------------- ----------- 8.4/11.9 MB 12.7 MB/s eta 0:00:01
     --------------------------------------  11.8/11.9 MB 13.5 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 12.8 MB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=a9ffa79565907a4d049e90124c146b75d07f18be7f621d67f7dc53a8974431ad
  Stored in directory: c:\users\hites\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [10]:
import mysql.connector

In [12]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [13]:
df = pd.read_sql_query('SELECT * FROM countrylanguage',conn)

C:\Users\hites\AppData\Local\Temp\ipykernel_20492\2304489313.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('SELECT * FROM countrylanguage',conn)

In [14]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [24]:
pd.read_sql_query('SELECT * FROM country WHERE LifeExpectancy > 70',conn)

C:\Users\hites\AppData\Local\Temp\ipykernel_20492\1669768444.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * FROM country WHERE LifeExpectancy > 70',conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,VCT,Saint Vincent and the Grenadines,North America,Caribbean,388.0,1979.0,114000,72.3,285.0,NaN,Saint Vincent and the Grenadines,Constitutional Monarchy,Elisabeth II,3066,VC
107,VEN,Venezuela,South America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,Venezuela,Federal Republic,Hugo Chávez Frías,3539,VE
108,VGB,"Virgin Islands, British",North America,Caribbean,151.0,NaN,21000,75.4,612.0,573.0,British Virgin Islands,Dependent Territory of the UK,Elisabeth II,537,VG
109,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the United States,US Territory,George W. Bush,4067,VI
110,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792,YU